/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestIctconscriptAdmissionRouteRouteImport } from './routes/test-ictconscript-admission.route'

const TestIctconscriptAdmissionRouteRoute =
  TestIctconscriptAdmissionRouteRouteImport.update({
    id: '/test-ictconscript-admission',
    path: '/test-ictconscript-admission',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/test-ictconscript-admission': typeof TestIctconscriptAdmissionRouteRoute
}
export interface FileRoutesByTo {
  '/test-ictconscript-admission': typeof TestIctconscriptAdmissionRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/test-ictconscript-admission': typeof TestIctconscriptAdmissionRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/test-ictconscript-admission'
  fileRoutesByTo: FileRoutesByTo
  to: '/test-ictconscript-admission'
  id: '__root__' | '/test-ictconscript-admission'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TestIctconscriptAdmissionRouteRoute: typeof TestIctconscriptAdmissionRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-ictconscript-admission': {
      id: '/test-ictconscript-admission'
      path: '/test-ictconscript-admission'
      fullPath: '/test-ictconscript-admission'
      preLoaderRoute: typeof TestIctconscriptAdmissionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  TestIctconscriptAdmissionRouteRoute: TestIctconscriptAdmissionRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
